### PR TITLE
Fixes according to review

### LINKED ISSUE #14: Fix according to review

### PR DESCRIPTION
**Pull request by jijinharidas**
fixes #14

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/constants.js [hunk 1]
```diff
@@ -3,13 +3,10 @@ import * as yup from "yup";
 export const NOTES_FORM_INITIAL_FORM_VALUES = {
   title: "",
   description: "",
+  role: null,
+  tags: null,
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/constants.js:7]: Couldn't we make the default value for `tags` as empty array `[]`? Wouldn't that be more appropriate from a business perspective?

Currently let's say we add two tags. Then we remove both of them. Then the value will be an empty array and not a `null` right?

File: app/javascript/src/components/Dashboard/Notes/constants.js [hunk 2]
```diff
@@ -48,6 +45,32 @@ export const ROLES = [
...
+    .array(
+      yup
+        .object()
+        .nullable()
+        .shape({
+          label: yup.string().oneOf(TAGS.map(tag => tag.label)),
+          value: yup.number().oneOf(TAGS.map(tag => tag.value)),
+        })
+    )
+    .nullable()
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/constants.js:69]: I believe this `nullable` is added over here since you set up the initial value as `null`. If we change it to `[]` then I don't think nullable is needed here.

**Review by yedhink — COMMENTED** [review]
@jijinharidas
